[pytest]
testpaths =
    pyfda/tests
    # integration
addopts = -v --ignore=pyfda/tests/test_fixpoint_helpers.py
             --ignore=pyfda/tests/test_fir_df.py

# Specifying the directory to ignore
# norecursedirs =  tests/in_progress tests/upcoming_modules

