---
name: build_flatpak
on:
  push:
    branches:
    - main
    # tags:
    # - 'v*' # Push a tag (this is not a release!)
  release:  # new version with tag
    types: [published]
  pull_request:
  page_build:
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-23.08
      options: --privileged
    steps:
    - name: Infos about github ref and trigger event
      run: |
        echo github.event_name:  ${{ github.event_name }}
        echo github.ref: ${{ github.ref }}
        echo github.ref_type:  ${{ github.ref_type }}
        echo github.ref_name:  ${{ github.ref_name }}

      # Example result for tagged release:
      #    github.event_name: release
      #    github.ref: refs/tags/v0.8.0a3
      #    github.ref_type: tag
      #    github.ref_name: v0.8.0a3

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build package
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: com.github.chipmuenk.pyfda.flatpak
        manifest-path: ressource/flatpak/com.github.chipmuenk.pyfda.yaml
        cache: false
        branch: development
        # Uploaded /__w/pyfda/pyfda/com.github.chipmuenk.pyfda.flatpak

  Validate_appdata_file:
    name: Validate appdata file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: validation
      # Command copied from flathub build process
      run: |
        sudo apt-get update
        sudo apt install flatpak
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y org.freedesktop.appstream-glib
        flatpak run --env=G_DEBUG=fatal-criticals org.freedesktop.appstream-glib validate ./ressource/linux/pyfda.appdata.xml

  release:
    # https://github.com/marvinpinto/actions/issues/177
    needs: [flatpak]
    runs-on: ubuntu-latest # does not matter which
    # if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        path: artifacts

    - name: list artifacts folder
      run: |
        echo "*** Show artifacts folder: ***"
        ls artifacts
        echo "*** Show artifacts/pyfda_Flatpak folder: ***"
        ls "artifacts/pyfda_Flatpak"
        # This doesn't work, path / file not found,
        # only pyfda_Flatpak.zip is downloaded and expanded, not the flatpak file
        # echo "*** Show artifacts/com.github.chipmuenk.pyfda-x86_64: ***"
        # ls "artifacts/com.github.chipmuenk.pyfda-x86_64"
        echo "*** Show com.github.chipmuenk.pyfda-x86_64: ***"
        ls "com.github.chipmuenk.pyfda-x86_64"

    # - name: Update GitHub prerelease
    #   if: ${{ github.ref == 'refs/heads/main' }}
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     automatic_release_tag: latest
    #     prerelease: true
    #     title: "Latest Build"
    #     files: |
    #       **/artifacts/pyfda Flatpak/com.github.chipmuenk.pyfda.yaml
    #       **/com.github.chipmuenk.pyfda-x86_64/*.flatpak

    - name: Update GitHub prerelease
      if: success() && github.ref_type != 'tag'
      uses: pyTooling/Actions/releaser@main
      with:
        tag: latest
        rm: false
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          artifacts/pyfda_Flatpak/com.github.chipmuenk.pyfda.yaml
          artifacts/com.github.chipmuenk.pyfda-x86_64/*.flatpak

    - name: Update versioned Github release
      if: success() && github.ref_type == 'tag'
      uses: pyTooling/Actions/releaser@main
      with:
        tag: ${{ github.ref_name }}
        rm: false
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          artifacts/pyfda_Flatpak/com.github.chipmuenk.pyfda.yaml
          artifacts/com.github.chipmuenk.pyfda-x86_64/*.flatpak

...
